#+TITLE: pdfdiff

naively try to figure out which articles of which documents correspond to which other articles.

* Prerequisites

** pandoc

your system package manager should be able to install ~pandoc~

** parallel

your system package manager should be able to install ~parallel~


* install and setup

#+begin_src shell
  git clone https://github.com/smucclaw/pdfdiff.git
  cd pdfdiff
#+end_src

In the ~pdfdiff~ directory we expect a directory ~FTA/~ to contain directories like these:

#+begin_example
┌─[20230306-17:47:56]   [mengwong@rosegold:~/src/smucclaw/pdfdiff/FTA]
└─[0] <> ll
total 24
drwx------@ 13 mengwong  staff     416 Mar  6 17:12 .
drwx------@  9 mengwong  staff     288 Mar  2 13:55 ..
drwx------@  8 mengwong  staff     256 Mar  6 17:45 1._Goods
drwx------@  6 mengwong  staff     192 Mar  6 17:38 2._Services
drwx------@  6 mengwong  staff     192 Mar  6 17:38 3._Investment
drwx------@  4 mengwong  staff     128 Mar  6 17:13 4._HS_Classification_&_Annotation
#+end_example

In my case, I downloaded a local copy of the ~FTA/~ directpry from the shared Google Drive

#+begin_example
  cp -rp ~/"Google-Drive/My Drive/CCLAW Centre for Computational Law/RPCL Research Team/Knowledge Management - Research & Working Docs/FTA Use Case/FTA" ./
#+end_example

This may be different for you based on how your Google Drive plugin is set up. You can use the Google Drive web UI to download the entire folder as a Zip file and work with a local copy.

Once that's done, you can run

#+begin_src shell
make
#+end_src

This should produce /matrix/ files that gauge the similarity of articles to each other.

#+begin_example
┌─[20230306-18:09:31]   [mengwong@rosegold:~/src/smucclaw/pdfdiff]
└─[0] <git:(main e77e631✱✈) > ll FTA/*/matrix*
-rw-r--r--@ 1 mengwong  staff  137229 Mar  6 17:50 FTA/1._Goods/matrix-RulesOfOrigin.org
-rw-r--r--@ 1 mengwong  staff   84130 Mar  6 17:46 FTA/1._Goods/matrix-TradeInGoods.org
-rw-r--r--@ 1 mengwong  staff  106508 Mar  6 17:51 FTA/2._Services/matrix-TradeInServices.org
-rw-r--r--@ 1 mengwong  staff   22146 Mar  6 17:51 FTA/3._Investment/matrix-Investment.org
#+end_example

From here, you can split the documents up by article, lay them out on a web page, and run diffs between them.


* ~stack run~ produces the following output file

FTA/1. Goods/SAFTA/Chapter 2 -Trade in Goods.md: read 28178 bytes
FTA/1. Goods/ANZSCEP/Chapter 2 - Trade in Goods.md: read 28884 bytes
FTA/1. Goods/CSFTA/Chapter 3 - Trade in Goods.md: read 3970 bytes
* matrix of similarity by Title: ANZSCEP(2.1--2.19) / CSFTA(4--9)
  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 2.10 2.11 2.12 2.13 2.14 2.15 2.16 2.17 2.18 2.19
4  15  13  45  15  19  14  34  76  23   21   17   15   26   15   16   23   18   14   41
5  47  52   0  47  42  48  31  67  43   41   45   44   38   45   44   41   44   46   34
6  12  11  47   0  10   5  38  80  23   24   17   14   26    6   15   27   16   14   40
7  23  28  37  25  25  26  29  72  26   22   26   23   26   24   22   30   24   24   36
8  42  45  41  38  36  40  41  69  38   39   41   42   31   40   30   30   34   36   37
9  19  22  41  19  21  22  32  73  22   23   21   20   24   19   18   26   17   17   38
* matrix of similarity by Body: ANZSCEP(2.1--2.19) / CSFTA(4--9)
   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9 2.10 2.11 2.12 2.13 2.14 2.15 2.16 2.17 2.18 2.19
4 4892   71  255  242  394  111  823  520 5290 2823  239 4864 1078  190  472 1286 2130  142   82
5 4714  216  100  199  323  169  701  416 5110 2645  234 4683  938  197  374 1132 1969  171  210
6 3952 1358 1198 1195 1144 1301 1031 1098 4322 2103 1221 3926 1041 1251 1091 1079 1564 1273 1352
7 4284  750  631  610  589  699  676  598 4647 2314  648 4246  805  668  580  959 1649  683  746
8 4363  618  511  503  491  571  619  508 4733 2369  530 4330  794  523  171  959 1723  560  620
9 4809  129  225  221  361  130  773  475 5207 2744  215 4781 1016  188  430 1216 2048  142  130
* matrix of similarity by Title: ANZSCEP(2.1--2.19) / SAFTA(1--18)
   2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 2.10 2.11 2.12 2.13 2.14 2.15 2.16 2.17 2.18 2.19
1    0  10  47  12  20  13  36  81  22   22   15   13   28   11   17   30   16   16   42
2   47  52   0  47  42  48  31  67  43   41   45   44   38   45   44   41   44   46   34
3   12  11  47   0  10   5  38  80  23   24   17   14   26    6   15   27   16   14   40
4   13  10  48   5  15   0  38  79  24   27   17   15   28   11   14   28   15   14   43
5   36  41  31  38  36  38   0  66  37   33   35   38   32   37   35   34   36   35   38
6   81  86  67  80  76  79  66   0  75   76   78   78   73   80   78   69   77   77   72
7   22  26  43  23  23  24  37  75   0   23   18   19   27   20   23   30   23   22   33
8   22  27  41  24  23  27  33  76  23    0   22   19   27   20   24   29   23   23   35
9   15  18  45  17  20  17  35  78  18   22    0   18   27   16   18   30   18   16   41
10  13  14  44  14  20  15  38  78  19   19   18    0   29   10   16   30   16   16   43
11  11  11  45   6  14  11  37  80  20   20   16   10   27    0   15   30   16   13   42
12  17  18  44  15  18  14  35  78  23   24   18   16   25   15    0   23    9    9   40
13  30  33  41  27  27  28  34  69  30   29   30   30   29   30   23    0   22   24   34
14  17  19  44  17  19  16  36  77  23   23   19   17   26   17    9   22    1   11   40
15  16  16  46  14  18  14  35  77  22   23   16   16   25   13    9   24   10    0   42
16  11  10  47  13  22  13  37  81  23   23   15   14   29   13   16   32   17   15   44
17  39  40  42  36  35  36  37  70  34   35   37   37   35   37   38   34   38   31   42
18  12  16  42  14  19  17  32  77  20   19   15   12   28   13   15   29   18   15   40
* matrix of similarity by Body: ANZSCEP(2.1--2.19) / SAFTA(1--18)
    2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9 2.10 2.11 2.12 2.13 2.14 2.15 2.16 2.17 2.18 2.19
1  1454 5357 5151 5157 5022 5292 4691 4908 4197 3918 5171 4038 4555 5212 4954 4434 4105 5264 5350
2  4678  248    1  220  325  198  685  414 5076 2617  238 4650  914  213  360 1113 1944  200  207
3  4581  343  284  184  329  308  634  400 4970 2539  308 4546  889  289  378 1051 1869  288  338
4  4790  143  198  208  339   66  754  463 5188 2727  220 4761  999  177  410 1192 2034  137  138
5  4229  807  677  679  640  761   10  582 4595 2265  698 4199  797  709  604  941 1670  738  806
6  4433  513  414  425  414  465  593    7 4826 2434  439 4414  839  431  430 1010 1780  449  513
7  3983 5218 5015 5014 4886 5154 4535 4765  124 3783 5029 3919 4408 5073 4811 4283 3954 5126 5215
8  3539 2804 2610 2626 2511 2745 2257 2422 3818   13 2632 3501 2149 2672 2406 2126 2024 2714 2798
9  4669  259  251  255  336  240  689  429 5062 2615   35 4640  932  233  385 1123 1937  234  257
10 3827 4871 4668 4669 4535 4806 4219 4431 3964 3507 4686  751 4071 4728 4462 3976 3623 4778 4867
11 4821  118  219  210  349  117  769  465 5219 2753  215 4793 1016  161  419 1220 2064  122  120
12 4479  457  359  351  377  417  609  430 4868 2411  392 4442  848  368    1 1006 1800  404  465
13 4813  124  223  220  349  123  768  479 5209 2747  204 4783 1017  184  427 1211 2052  127  123
14 3883 1600 1443 1443 1369 1540 1220 1314 4218 2064 1460 3843 1185 1492 1327 1200 1336 1516 1595
15 4785  144  198  202  342  124  744  447 5184 2718  211 4758  992  162  403 1191 2027    7  141
16 4873   81  207  235  387  120  813  513 5274 2804  231 4848 1063  190  465 1272 2115  138    2
17 4735  199  215  221  342  173  733  445 5131 2679  224 4707  967  196  393 1160 1990  176  199
18 3666 2283 2096 2107 2019 2222 1802 1946 4003 2045 2117 3638 1734 2156 1948 1710 1775 2193 2274
* matrix of similarity by Title: CSFTA(4--9) / ANZSCEP(2.1--2.19)
      4  5  6  7  8  9
2.1  15 47 12 23 42 19
2.2  13 52 11 28 45 22
2.3  45  0 47 37 41 41
2.4  15 47  0 25 38 19
2.5  19 42 10 25 36 21
2.6  14 48  5 26 40 22
2.7  34 31 38 29 41 32
2.8  76 67 80 72 69 73
2.9  23 43 23 26 38 22
2.10 21 41 24 22 39 23
2.11 17 45 17 26 41 21
2.12 15 44 14 23 42 20
2.13 26 38 26 26 31 24
2.14 15 45  6 24 40 19
2.15 16 44 15 22 30 18
2.16 23 41 27 30 30 26
2.17 18 44 16 24 34 17
2.18 14 46 14 24 36 17
2.19 41 34 40 36 37 38
* matrix of similarity by Body: CSFTA(4--9) / ANZSCEP(2.1--2.19)
        4    5    6    7    8    9
2.1  4892 4714 3952 4284 4363 4809
2.2    71  216 1358  750  618  129
2.3   255  100 1198  631  511  225
2.4   242  199 1195  610  503  221
2.5   394  323 1144  589  491  361
2.6   111  169 1301  699  571  130
2.7   823  701 1031  676  619  773
2.8   520  416 1098  598  508  475
2.9  5290 5110 4322 4647 4733 5207
2.10 2823 2645 2103 2314 2369 2744
2.11  239  234 1221  648  530  215
2.12 4864 4683 3926 4246 4330 4781
2.13 1078  938 1041  805  794 1016
2.14  190  197 1251  668  523  188
2.15  472  374 1091  580  171  430
2.16 1286 1132 1079  959  959 1216
2.17 2130 1969 1564 1649 1723 2048
2.18  142  171 1273  683  560  142
2.19   82  210 1352  746  620  130
* matrix of similarity by Title: CSFTA(4--9) / SAFTA(1--18)
    4  5  6  7  8  9
1  15 47 12 23 42 19
2  45  0 47 37 41 41
3  15 47  0 25 38 19
4  14 48  5 26 40 22
5  34 31 38 29 41 32
6  76 67 80 72 69 73
7  23 43 23 26 38 22
8  21 41 24 22 39 23
9  17 45 17 26 41 21
10 15 44 14 23 42 20
11 15 45  6 24 40 19
12 16 44 15 22 30 18
13 23 41 27 30 30 26
14 19 44 17 25 34 17
15 14 46 14 24 36 17
16 15 47 13 24 42 20
17 35 42 36 35 40 33
18 16 42 14 21 40 16
* matrix of similarity by Body: CSFTA(4--9) / SAFTA(1--18)
      4    5    6    7    8    9
1  5369 5189 4401 4750 4829 5286
2   254   99 1198  631  511  224
3   353  285 1140  576  488  323
4   140  166 1278  684  560  124
5   815  695 1031  670  614  765
6   519  415 1100  598  509  473
7  5230 5050 4268 4592 4674 5147
8  2816 2639 2096 2307 2362 2737
9   264  251 1203  634  517  238
10 4883 4702 3936 4264 4345 4799
11  113  192 1306  698  578  131
12  471  373 1090  579  171  429
13  122  200 1298  702  585  132
14 1610 1469 1200 1225 1258 1535
15  144  168 1271  679  555  145
16   80  209 1351  745  619  130
17  199  201 1246  654  535  185
18 2293 2126 1695 1842 1867 2212
* matrix of similarity by Title: SAFTA(1--18) / ANZSCEP(2.1--2.19)
      1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
2.1   0 47 12 13 36 81 22 22 15 13 11 17 30 17 16 11 39 12
2.2  10 52 11 10 41 86 26 27 18 14 11 18 33 19 16 10 40 16
2.3  47  0 47 48 31 67 43 41 45 44 45 44 41 44 46 47 42 42
2.4  12 47  0  5 38 80 23 24 17 14  6 15 27 17 14 13 36 14
2.5  20 42 10 15 36 76 23 23 20 20 14 18 27 19 18 22 35 19
2.6  13 48  5  0 38 79 24 27 17 15 11 14 28 16 14 13 36 17
2.7  36 31 38 38  0 66 37 33 35 38 37 35 34 36 35 37 37 32
2.8  81 67 80 79 66  0 75 76 78 78 80 78 69 77 77 81 70 77
2.9  22 43 23 24 37 75  0 23 18 19 20 23 30 23 22 23 34 20
2.10 22 41 24 27 33 76 23  0 22 19 20 24 29 23 23 23 35 19
2.11 15 45 17 17 35 78 18 22  0 18 16 18 30 19 16 15 37 15
2.12 13 44 14 15 38 78 19 19 18  0 10 16 30 17 16 14 37 12
2.13 28 38 26 28 32 73 27 27 27 29 27 25 29 26 25 29 35 28
2.14 11 45  6 11 37 80 20 20 16 10  0 15 30 17 13 13 37 13
2.15 17 44 15 14 35 78 23 24 18 16 15  0 23  9  9 16 38 15
2.16 30 41 27 28 34 69 30 29 30 30 30 23  0 22 24 32 34 29
2.17 16 44 16 15 36 77 23 23 18 16 16  9 22  1 10 17 38 18
2.18 16 46 14 14 35 77 22 23 16 16 13  9 24 11  0 15 31 15
2.19 42 34 40 43 38 72 33 35 41 43 42 40 34 40 42 44 42 40
* matrix of similarity by Body: SAFTA(1--18) / ANZSCEP(2.1--2.19)
        1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18
2.1  1454 4678 4581 4790 4229 4433 3983 3539 4669 3827 4821 4479 4813 3883 4785 4873 4735 3666
2.2  5357  248  343  143  807  513 5218 2804  259 4871  118  457  124 1600  144   81  199 2283
2.3  5151    1  284  198  677  414 5015 2610  251 4668  219  359  223 1443  198  207  215 2096
2.4  5157  220  184  208  679  425 5014 2626  255 4669  210  351  220 1443  202  235  221 2107
2.5  5022  325  329  339  640  414 4886 2511  336 4535  349  377  349 1369  342  387  342 2019
2.6  5292  198  308   66  761  465 5154 2745  240 4806  117  417  123 1540  124  120  173 2222
2.7  4691  685  634  754   10  593 4535 2257  689 4219  769  609  768 1220  744  813  733 1802
2.8  4908  414  400  463  582    7 4765 2422  429 4431  465  430  479 1314  447  513  445 1946
2.9  4197 5076 4970 5188 4595 4826  124 3818 5062 3964 5219 4868 5209 4218 5184 5274 5131 4003
2.10 3918 2617 2539 2727 2265 2434 3783   13 2615 3507 2753 2411 2747 2064 2718 2804 2679 2045
2.11 5171  238  308  220  698  439 5029 2632   35 4686  215  392  204 1460  211  231  224 2117
2.12 4038 4650 4546 4761 4199 4414 3919 3501 4640  751 4793 4442 4783 3843 4758 4848 4707 3638
2.13 4555  914  889  999  797  839 4408 2149  932 4071 1016  848 1017 1185  992 1063  967 1734
2.14 5212  213  289  177  709  431 5073 2672  233 4728  161  368  184 1492  162  190  196 2156
2.15 4954  360  378  410  604  430 4811 2406  385 4462  419    1  427 1327  403  465  393 1948
2.16 4434 1113 1051 1192  941 1010 4283 2126 1123 3976 1220 1006 1211 1200 1191 1272 1160 1710
2.17 4105 1944 1869 2034 1670 1780 3954 2024 1937 3623 2064 1800 2052 1336 2027 2115 1990 1775
2.18 5264  200  288  137  738  449 5126 2714  234 4778  122  404  127 1516    7  138  176 2193
2.19 5350  207  338  138  806  513 5215 2798  257 4867  120  465  123 1595  141    2  199 2274
* matrix of similarity by Title: SAFTA(1--18) / CSFTA(4--9)
   1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
4 15 45 15 14 34 76 23 21 17 15 15 16 23 19 14 15 35 16
5 47  0 47 48 31 67 43 41 45 44 45 44 41 44 46 47 42 42
6 12 47  0  5 38 80 23 24 17 14  6 15 27 17 14 13 36 14
7 23 37 25 26 29 72 26 22 26 23 24 22 30 25 24 24 35 21
8 42 41 38 40 41 69 38 39 41 42 40 30 30 34 36 42 40 40
9 19 41 19 22 32 73 22 23 21 20 19 18 26 17 17 20 33 16
* matrix of similarity by Body: SAFTA(1--18) / CSFTA(4--9)
     1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18
4 5369  254  353  140  815  519 5230 2816  264 4883  113  471  122 1610  144   80  199 2293
5 5189   99  285  166  695  415 5050 2639  251 4702  192  373  200 1469  168  209  201 2126
6 4401 1198 1140 1278 1031 1100 4268 2096 1203 3936 1306 1090 1298 1200 1271 1351 1246 1695
7 4750  631  576  684  670  598 4592 2307  634 4264  698  579  702 1225  679  745  654 1842
8 4829  511  488  560  614  509 4674 2362  517 4345  578  171  585 1258  555  619  535 1867
9 5286  224  323  124  765  473 5147 2737  238 4799  131  429  132 1535  145  130  185 2212
* FTA/1. Goods/ANZSCEP/Chapter 2 - Trade in Goods.md
**  __PREAMBLE
:length: 53
*** body
CHAPTER 2: TRADE IN GOODS
=========================

*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = ?(__PREAMBLE)
*** SAFTA: most similar Title = ?(__PREAMBLE)
*** SAFTA: most similar Body = ?(__PREAMBLE)

** 2.1 Definitions
:length: 4980
*** body

For the purposes of this Chapter:

**AD Agreement** means the *Agreement on Implementation of Article VI of the General Agreement on Tariffs and Trade 1994*, set out in Annex 1A to the WTO Agreement;

**advertising films and recordings** means recorded visual media or audio materials, consisting essentially of images or sound, showing the nature or operation of goods or services offered for sale or lease by a person of a Party, that are of a kind suitable for exhibition to prospective customers but not for broadcast to the general public;

**Agreement on Agriculture** means the *Agreement on Agriculture*, set out in Annex 1A to the WTO Agreement;

**commercial samples of negligible value** means commercial or trade samples: having a value, individually or in the aggregate as shipped, of not more than one U.S. dollar or the equivalent amount in the currency of either Party; or so marked, torn, perforated or otherwise treated that they are unsuitable for sale or for use except as commercial samples;

**consular transactions** means requirements that goods of a Party intended for export to the territory of the other Party must first be submitted to the supervision of the consul of the importing Party in the territory of the exporting Party for the purposes of obtaining consular invoices or consular visas for commercial invoices, certificates of origin, manifests, shippers' export declarations, or any other customs documentation required on or in connection with importation;

**consumed** means, with respect to a good:

(a) actually consumed; or

(b) further processed or manufactured:

    i.  so as to result in a substantial change in the value, form or use of the good; or

    ii. in the production of another good;

**distributor** means a person of a Party who is responsible for the commercial distribution, agency, concession or representation in the territory of that Party of goods of the other Party;

**duty-free** means free of customs duty;

**export subsidy** means a subsidy as defined in Article 3 of the SCM Agreement and includes export subsidies listed in Article 9 of the Agreement on Agriculture;

**goods admitted for sports purposes** means sports requisites admitted into the territory of the importing Party for use in sports contests, demonstrations or training in the territory of that Party;

**goods intended for display or demonstration** includes their component parts, ancillary apparatuses and accessories;

**import licensing** means an administrative procedure requiring the submission of an application or other documentation, other than that generally required for customs clearance purposes, to the relevant administrative body of the importing Party as a prior condition for importation into the territory of that Party;

**Import Licensing Agreement** means the *Agreement on Import Licensing Procedures*, set out in Annex 1A to the WTO Agreement;

**measure** includes any law, regulation, procedure, requirement or practice;

**performance requirement** means a requirement that:

(a) a given level or percentage of goods or services be exported;

(b) domestic goods or services of the Party granting a waiver of customs duties or an import licence be substituted for imported goods;

(c) a person benefiting from a waiver of customs duties or a requirement for an import licence purchase other goods or services in the territory of the Party that grants the waiver of customs duties or the import licence or accord a preference to domestically produced goods;

(d) a person benefiting from a waiver of customs duties or a requirement for an import licence produce goods or supply services in the territory of the Party that grants the waiver of customs duties or the import licence with a given level or percentage of domestic content; or

(e) relates in any way the volume or value of imports to the volume or value of exports or to the amount of foreign exchange inflows,

but does not include a requirement that an imported good be:

(f) subsequently exported;

(g) used as a material in the production of another good that is subsequently exported;

(h) substituted by an identical or similar good used as a material in the production of another good that is subsequently exported; or

(i) substituted by an identical or similar good that is subsequently exported;

**printed advertising materials** means those goods classified in Chapter 49 of the Harmonized System, including brochures, pamphlets, leaflets, trade catalogues, yearbooks published by trade associations, tourist promotional materials, and posters, that are used to promote, publicise or advertise a good or service, are essentially intended to advertise a good or service and are supplied free of charge;

**Safeguards Agreement** means the *Agreement on Safeguards*, set out in Annex 1A to the WTO Agreement; and

**SCM Agreement** means the *Agreement on Subsidies and Countervailing Measures*, set out in Annex 1A to the WTO Agreement.

*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 6(Customs Duties)
*** SAFTA: most similar Title = 1(Definitions)
*** SAFTA: most similar Body = 1(Definitions)

** 2.2 Scope
:length: 100
*** body

Except as otherwise provided, this Chapter shall apply to trade in all goods between the Parties.

*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 4(Scope and Coverage)
*** SAFTA: most similar Title = ?(__PREAMBLE)
*** SAFTA: most similar Body = 16(Transparency)

** 2.3 National Treatment on Internal Taxation and Regulation
:length: 314
*** body

Each Party shall accord national treatment to the goods of the other Party in accordance with Article III of the GATT 1994, including its interpretative notes. To this end, Article III of the GATT 1994 and its interpretative notes are incorporated into and shall form part of this Agreement, *mutatis mutandis*.

*** CSFTA: most similar Title = 5(National Treatment on Internal Taxation and Regulation)
*** CSFTA: most similar Body = 5(National Treatment on Internal Taxation and Regulation)
*** SAFTA: most similar Title = 2(National Treatment on Internal Taxation and Regulation)
*** SAFTA: most similar Body = 2(National Treatment on Internal Taxation and Regulation)

** 2.4 Customs Duties
:length: 307
*** body

1.  Each Party shall eliminate all customs duties on originating goods of the other Party at the date of entry into force of this Agreement and such customs duties shall remain free after that date.

2.  Each Party shall classify goods traded between the Parties in conformity with the Harmonized System.

*** CSFTA: most similar Title = 6(Customs Duties)
*** CSFTA: most similar Body = 5(National Treatment on Internal Taxation and Regulation)
*** SAFTA: most similar Title = 3(Customs Duties)
*** SAFTA: most similar Body = 3(Customs Duties)

** 2.5 Waiver of Customs Duties
:length: 466
*** body

1.  Neither Party shall adopt any new waiver of a customs duty, or expand with respect to an existing recipient or extend to any new recipient the application of an existing waiver of a

customs duty, that is conditioned, explicitly or implicitly, on the fulfilment of a performance requirement.

2.  Neither Party shall, explicitly or implicitly, condition the continuation of any existing waiver of a customs duty on the fulfilment of a performance requirement.

*** CSFTA: most similar Title = 6(Customs Duties)
*** CSFTA: most similar Body = 5(National Treatment on Internal Taxation and Regulation)
*** SAFTA: most similar Title = 3(Customs Duties)
*** SAFTA: most similar Body = 2(National Treatment on Internal Taxation and Regulation)

** 2.6 Customs Value
:length: 168
*** body

Each Party shall determine the customs value of goods traded between the Parties in accordance with Article VII of the GATT 1994 and the Customs Valuation Agreement.

*** CSFTA: most similar Title = 6(Customs Duties)
*** CSFTA: most similar Body = 4(Scope and Coverage)
*** SAFTA: most similar Title = 4(Customs Value)
*** SAFTA: most similar Body = 4(Customs Value)

** 2.7 Goods Re-entered after Repair and Alteration
:length: 904
*** body

1.  Neither Party shall apply a customs duty to a good, regardless of its origin, that re- enters the Party's territory after that good has been temporarily exported from the Party's territory to the territory of the other Party for repair or alteration, regardless of whether that repair or alteration could have been performed in the territory of the Party from which the good was exported for repair or alteration or has increased the value of the good.

2.  Neither Party shall apply a customs duty to a good, regardless of its origin, admitted temporarily from the territory of the other Party for repair or alteration.

3.  For the purposes of this Article, **repair or alteration** does not include an operation or process that:

    a.  destroys a good's essential characteristics or creates a new or commercially different good; or

    b.  transforms an unfinished good into a finished good.

*** CSFTA: most similar Title = 7(Accelerated Tariff Elimination)
*** CSFTA: most similar Body = 8(Quantitative Restrictions and Non-Tariff Measures)
*** SAFTA: most similar Title = 5(Goods Re-entered after Repair and Alteration)
*** SAFTA: most similar Body = 5(Goods Re-entered after Repair and Alteration)

** 2.8 Duty-Free Entry of Commercial Samples of Negligible Value and Printed Advertising Material
:length: 593
*** body

Each Party shall grant duty-free entry to commercial samples of negligible value and printed advertising material imported from the territory of the other Party, regardless of their origin, but may require that:

(a) commercial samples of negligible value be imported solely for the solicitation of orders for goods or services provided from the territory of the other Party or a non-Party; or

(b) printed advertising material be imported in packets that each contain no more than one copy of the material and that neither that material nor those packets form part of a larger consignment.

*** CSFTA: most similar Title = 5(National Treatment on Internal Taxation and Regulation)
*** CSFTA: most similar Body = 5(National Treatment on Internal Taxation and Regulation)
*** SAFTA: most similar Title = 6(Duty-Free Entry of Commercial Samples of Negligible Value and Printed Advertising Material)
*** SAFTA: most similar Body = 6(Duty-Free Entry of Commercial Samples of Negligible Value and Printed Advertising Material)

** 2.9 Temporary Admission of Goods
:length: 5378
*** body

1.  Each Party shall grant duty-free temporary admission for the following goods, regardless of their origin:

    a.  professional equipment, including equipment for the press or television, software, and broadcasting and cinematographic equipment, that is necessary for carrying out the business activity, trade or profession of a person who qualifies for temporary entry pursuant to the laws and regulations of the importing Party;

    b.  goods intended for display or demonstration;

    c.  commercial samples and advertising films and recordings; and

    d.  goods admitted for sports purposes.

2.  Each Party shall, at the request of the person concerned and for reasons its customs administration considers valid, extend the time limit for duty-free temporary admission beyond the period initially fixed.

3.  Neither Party shall condition the duty-free temporary admission of the goods referred to in paragraph 1, other than to require that those goods:

    a.  be used solely by or under the personal supervision of a national of the other Party in the exercise of the business activity, trade, profession or sport of that national of the other Party;

    b.  not be sold or leased while in its territory;

    c.  be accompanied by a security in an amount no greater than the charges that would otherwise be owed on entry or final importation, releasable on exportation of the goods;

    d.  be capable of identification when imported and exported;

    e.  be exported on the departure of the national referred to in subparagraph (a), or within any other period reasonably related to the purpose of the temporary admission that the Party may establish, or within one year, unless extended;

    f.  be admitted in no greater quantity than is reasonable for their intended use; and

    g.  be otherwise admissible into the Party's territory under its laws and regulations.

4.  Each Party shall grant duty-free temporary admission for containers and pallets regardless of their origin, that are in use or to be used in the shipment of goods in international traffic.

    a.  For the purposes of this paragraph, **container** means an article of transport equipment that is: fully or partially enclosed to constitute a compartment intended for containing goods; substantial and has an internal volume of one cubic metre or more; of a permanent character and accordingly strong enough to be suitable for repeated use; used in significant numbers in international traffic; specially designed to facilitate the carriage of goods by more than one mode of transport without intermediate reloading; and designed both for ready handling, particularly when being transferred from one mode of transport to another, and to be easy to fill and to empty, but does not include vehicles, accessories or spare parts of vehicles or packaging.

    b.  For the purposes of this paragraph, **pallet** means a small, portable platform, which consists of two decks separated by bearers or a single deck supported by feet, on which goods can be moved, stacked, and stored, and which is designed essentially for handling by means of fork lift trucks, pallet trucks, or other jacking devices.

5.  If any condition that a Party imposes under paragraph 3 has not been fulfilled, the Party may apply the customs duty and any other charge that would normally be owed on the good in addition to any other charges or penalties provided for under its laws and regulations.

6.  Each Party shall adopt and maintain procedures providing for the expeditious release of goods admitted under this Article. To the extent possible, those procedures shall provide that when a good admitted under this Article accompanies a national of the other Party who is seeking temporary entry, the good shall be released simultaneously with the entry of that national.

7.  Each Party shall permit a good temporarily admitted under this Article to be exported through a customs port other than the port through which it was admitted.

8.  Each Party shall, in accordance with its laws and regulations, provide that the importer or other person responsible for a good admitted under this Article shall not be liable for failure to export the good on presentation of satisfactory proof to the importing Party that the good was destroyed within the period fixed for temporary admission, including any lawful extension.

9.  Subject to Chapter 7 (Investment) and Chapter 8 (Services):

    a.  each Party shall allow a container used in international traffic that enters its territory from the territory of the other Party to exit its territory on any route that is reasonably related to the economic and prompt departure of that container;

    b.  neither Party shall require any security or impose any penalty or charge solely by reason of any difference between the customs port of entry and the customs port of departure of a container;

    c.  neither Party shall condition the release of any obligation, including any security, that it imposes in respect of the entry of a container into its territory on the exit of that container through any particular customs port of departure; and

    d.  neither Party shall require that the carrier bringing a container from the territory of the other Party into its territory be the same carrier that takes such container to the territory of the other Party.

*** CSFTA: most similar Title = 9(State Trading Enterprises)
*** CSFTA: most similar Body = 6(Customs Duties)
*** SAFTA: most similar Title = 7(Temporary Admission of Goods)
*** SAFTA: most similar Body = 7(Temporary Admission of Goods)

** 2.10 Import and Export Restrictions
:length: 2911
*** body

1.  Except as otherwise provided in this Agreement, neither Party shall adopt or maintain any prohibition or restriction on the importation of any good of the other Party or on the exportation or sale for export of any good destined for the territory of the other Party, except in accordance with Article XI of the GATT 1994 and its interpretative notes, and to this end Article XI of the GATT 1994 and its interpretative notes are incorporated into and made part of this Agreement, *mutatis mutandis*.

2.  The Parties understand that the GATT 1994 rights and obligations incorporated by paragraph 1 prohibit, in any circumstances in which any other form of restriction is prohibited, a Party from adopting or maintaining:

    a.  export and import price requirements, except as permitted in enforcement of countervailing and antidumping duty orders and undertakings;

    b.  import licensing conditioned on the fulfilment of a performance requirement; or

    c.  voluntary export restraints inconsistent with Article VI of the GATT 1994, as implemented under Article 18 of the SCM Agreement and Article 8.1 of the AD Agreement.

3.  For greater certainty, paragraph 1 shall apply to the importation of commercial cryptographic goods.

4.  For the purposes of paragraph 3, **commercial cryptographic goods** means any good implementing or incorporating cryptography, if the good is not designed or modified specifically for government use and is sold or otherwise made available to the public.

5.  In the event that a Party adopts or maintains a prohibition or restriction on the importation from or exportation to a non-Party of a good, no provision of this Agreement shall be construed to prevent that Party from:

    a.  limiting or prohibiting the importation of the good of the non-Party from the territory of the other Party; or

    b.  requiring, as a condition for exporting the good of that Party to the territory of the other Party, that the good not be re-exported to the non-Party, directly or indirectly, without being consumed in the territory of the other Party.

6.  In the event that a Party adopts or maintains a prohibition or restriction on the importation of a good from a non-Party, it shall, on the request of the other Party, consult with the other Party with a view to avoiding undue interference with or distortion of pricing, marketing, or distribution arrangements in that other Party.

7.  Neither Party shall, as a condition for engaging in importation or for the importation of a good, require a person of the other Party to establish or maintain a contractual or other relationship with a distributor in its territory.

8.  For greater certainty, paragraph 7 does not prevent a Party from requiring a person referred to in that paragraph to designate a point of contact for the purposes of facilitating communications between its regulatory authorities and that person.

*** CSFTA: most similar Title = 4(Scope and Coverage)
*** CSFTA: most similar Body = 6(Customs Duties)
*** SAFTA: most similar Title = 8(Import and Export Restrictions)
*** SAFTA: most similar Body = 8(Import and Export Restrictions)

** 2.11 Remanufactured Goods
:length: 298
*** body

1.  For greater certainty, Article 2.10.1 shall apply to prohibitions and restrictions on the importation of remanufactured goods.

2.  If a Party adopts or maintains measures prohibiting or restricting the importation of used goods, it shall not apply those measures to remanufactured goods.^1^

*** CSFTA: most similar Title = 4(Scope and Coverage)
*** CSFTA: most similar Body = 9(State Trading Enterprises)
*** SAFTA: most similar Title = 9(Remanufactured Goods)
*** SAFTA: most similar Body = 9(Remanufactured Goods)

** 2.12 Import Licensing
:length: 4952
*** body

1.  Neither Party shall adopt or maintain a measure that is inconsistent with the Import Licensing Agreement.

2.  Promptly after the Protocol enters into force for a Party, that Party shall notify the other Party of its existing import licensing procedures, if any. The notice shall include the information specified in Article 5.2 of the Import Licensing Agreement and any information required under paragraph 6.

^1^ For greater certainty, subject to its obligations under this Agreement and the WTO Agreement, a Party may require that remanufactured goods:

a.  be identified as such for distribution or sale in its territory; and

b.  meet all applicable technical requirements that apply to equivalent goods in new condition.

```{=html}
<!-- -->
```
3.  A Party shall be deemed to be in compliance with paragraph 2 with respect to an existing import licensing procedure if:

    a.  it has notified that procedure to the WTO Committee on Import Licensing provided for in Article 4 of the Import Licensing Agreement together with the information specified in Article 5.2 of that agreement;

    b.  in the most recent annual submission, due before the date of entry into force of the Protocol for that Party, to the WTO Committee on Import Licensing in response to the annual questionnaire on import licensing procedures described in Article 7.3 of the Import Licensing Agreement, it has provided, with respect to that procedure, the information requested in that questionnaire; and

    c.  it has included in either the notice described in subparagraph (a) or the annual submission described in subparagraph (b) any information required to be notified to the other Party under paragraph 6.

4.  Each Party shall comply with Article 1.4(a) of the Import Licensing Agreement with respect to any new or modified import licensing procedure. Each Party shall also publish on an official government website any information that it is required to publish under Article 1.4(a) of the Import Licensing Agreement.

5.  Each Party shall notify the other Party of any new import licensing procedures it adopts and any modifications it makes to its existing import licensing procedures, if possible, no later than 60 days before the new procedure or modification takes effect. In no case shall a Party provide the notification later than 60 days after the date of its publication. The notification shall include any information required under paragraph 6. A Party shall be deemed to be in compliance with this obligation if it notifies a new import licensing procedure or a modification to an existing import licensing procedure to the WTO Committee on Import Licensing in accordance with Article 5.1, Article 5.2 or Article 5.3 of the Import Licensing Agreement and includes in its notification any information required to be notified to the other Party under paragraph 6.

6.  \(a\) A notice under paragraph 2, paragraph 3 or paragraph 5 shall state if, under any import licensing procedure that is a subject of the notice:

```{=html}
<!-- -->
```
(i) the terms of an import licence for any product limit the permissible end users of the product; or

(ii) the Party imposes any of the following conditions on eligibility for obtaining a licence to import any product:

     A.  membership in an industry association;

     B.  approval by an industry association of the request for an import licence;

     C.  a history of importing the product or similar products;

     D.  minimum importer or end user production capacity;

     E.  minimum importer or end user registered capital; or

     F.  a contractual or other relationship between the importer and a distributor in the Party's territory.

```{=html}
<!-- -->
```
(b) A notice that states, under subparagraph (a), that there is a limitation on permissible end users or a licence-eligibility condition shall:

    i.  list all products for which the end-user limitation or licence eligibility condition applies; and

    ii. describe the end-user limitation or licence-eligibility condition.

```{=html}
<!-- -->
```
7.  Each Party shall respond within 60 days to a reasonable enquiry from the other Party concerning its licensing rules and its procedures for the submission of an application for an import licence, including the eligibility of persons, firms and institutions to make an application, the administrative body or bodies to be approached and the list of products subject to the licensing requirement.

8.  If a Party denies an import licence application with respect to a good of the other Party, it shall, on request of the applicant and within a reasonable period after receiving the request, provide the applicant with a written explanation of the reason for the denial.

9.  Neither Party shall apply an import licensing procedure to a good of the other Party unless it has, with respect to that procedure, met the requirements of paragraph 2 or paragraph 4, as applicable.

*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 6(Customs Duties)
*** SAFTA: most similar Title = 10(Import Licensing)
*** SAFTA: most similar Body = 10(Import Licensing)

** 2.13 Administrative Fees and Formalities
:length: 1163
*** body

1.  Each Party shall ensure, in accordance with Article VIII:1 of GATT 1994 and its interpretative notes, that all fees and charges of whatever character (other than export taxes, customs duties, charges equivalent to an internal tax or other internal charge applied consistently with Article III:2 of GATT 1994, and antidumping and countervailing duties) imposed on or in connection with importation or exportation are limited in amount to the approximate cost of services rendered and do not represent an indirect protection to domestic goods or a taxation of imports or exports for fiscal purposes.

2.  Neither Party shall require consular transactions, including related fees and charges, in connection with the importation of a good of another Party.

3.  Each Party shall make publicly available online a current list of the fees and charges it imposes in connection with importation or exportation.

4.  Neither Party shall levy fees and charges on or in connection with importation or exportation on an ad valorem basis.

5.  Each Party shall periodically review its fees and charges, with a view to reducing their number and diversity if practicable.

*** CSFTA: most similar Title = 9(State Trading Enterprises)
*** CSFTA: most similar Body = 8(Quantitative Restrictions and Non-Tariff Measures)
*** SAFTA: most similar Title = 12(Non-tariff Measures)
*** SAFTA: most similar Body = 5(Goods Re-entered after Repair and Alteration)

** 2.14 Export Duties
:length: 249
*** body

A Party shall not adopt or maintain any duty, tax, or other charge on the export of any good to the territory of the other Party, unless such duty, tax or charge is adopted or maintained on any such good when destined for domestic consumption.^2^

*** CSFTA: most similar Title = 6(Customs Duties)
*** CSFTA: most similar Body = 9(State Trading Enterprises)
*** SAFTA: most similar Title = 11(Export Duties)
*** SAFTA: most similar Body = 11(Export Duties)

** 2.15 Non-tariff Measures
:length: 545
*** body

1.  Neither Party shall adopt or maintain any non-tariff measures on the importation of any good of the other Party or on the exportation of any good destined for the territory of the other Party except in accordance with its WTO rights and obligations or in accordance with this Agreement*.*

2.  Each Party shall ensure the transparency of its non-tariff measures permitted under paragraph 1 and that they are not prepared, adopted or applied with a view to or with the effect of creating unnecessary obstacles to trade between the Parties.

*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 8(Quantitative Restrictions and Non-Tariff Measures)
*** SAFTA: most similar Title = 12(Non-tariff Measures)
*** SAFTA: most similar Body = 12(Non-tariff Measures)

** 2.16 Subsidies and Countervailing Measures
:length: 1371
*** body

1.  Each Party shall prohibit export subsidies on all goods, including agricultural goods.

2.  If either Party grants or maintains any subsidy which operates to increase exports of any product from, or to reduce imports of any product into, its territory, it shall notify the other Party to the extent and nature of the subsidisation, of the estimated effect of the subsidisation on the quantity of the affected product or products imported into or exported from its territory and of the circumstances making the subsidisation necessary. In any case in which it is determined that serious prejudice to the interests of the other Party is caused or threatened by any subsidisation, the Party granting the subsidy shall, upon request, discuss with the other Party the possibility of limiting the subsidisation. This paragraph shall be applied in conjunction with the relevant applicable provisions of the GATT 1994 and the SCM Agreement.

3.  The Parties reaffirm their commitment to abide by the SCM Agreement in respect of actionable subsidies.

^2^ For greater certainty, this Article shall not apply to fees, charges, formalities and requirements on the exportation of goods imposed consistent with Article VIII of GATT 1994.

4.  Each Party shall seek to avoid causing adverse effects to the interests of the other Party in terms of Article 5 of the SCM Agreement.

*** CSFTA: most similar Title = 4(Scope and Coverage)
*** CSFTA: most similar Body = 7(Accelerated Tariff Elimination)
*** SAFTA: most similar Title = 13(Subsidies and Countervailing Measures)
*** SAFTA: most similar Body = 5(Goods Re-entered after Repair and Alteration)

** 2.17 Antidumping Measures
:length: 2216
*** body

1.  Both Parties are Members of the AD Agreement. For the purposes of trade between the Parties, the following changes are agreed in terms of implementation of the AD Agreement in order to bring greater discipline to antidumping investigations and to minimise the opportunities to use antidumping in an arbitrary or protectionist manner:

    a.  the *de minimis* dumping margin of two per cent expressed as a percentage of the export price below which no antidumping duties can be imposed provided for in Article 5.8 of the AD Agreement is raised to five per cent;

    b.  the new *de minimis* margin of five per cent established in subparagraph (a) is applied not only in new cases but also in refund and review cases;

    c.  the maximum volume of dumped imports from the exporting Party which shall normally be regarded as negligible under Article 5.8 of the AD Agreement is increased from three per cent to five per cent of imports of the like product in the importing Party. Existing cumulation provisions under Article 5.8 continue to apply;

    d.  the time frame to be used for determining the volume of dumped imports under the preceding subparagraphs shall be representative of the imports of both dumped and non-dumped goods for a reasonable period. Such reasonable period shall normally be at least 12 months;

    e.  the period for review or termination of antidumping duties provided for in Article 11.3 of the AD Agreement is reduced from five years to three years.

2.  Notification procedures shall be as follows:

    a.  immediately following the acceptance of a properly documented application from an industry in one Party for the initiation of an antidumping investigation in respect of goods from the other Party, the Party that has accepted the properly documented application shall immediately inform the other Party;

    b.  if a Party considers that, in accordance with Article 5 of the AD Agreement, there is sufficient evidence to justify the initiation of an antidumping investigation, it shall give written notice to the other Party in accordance with Article 12.1 of the AD Agreement and observe the requirements of Article

17.2 of the AD Agreement concerning consultations.

*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 6(Customs Duties)
*** SAFTA: most similar Title = 14(Anti-Dumping Measures)
*** SAFTA: most similar Body = 14(Anti-Dumping Measures)

** 2.18 Safeguard Measures
:length: 193
*** body

No Party shall initiate or take any safeguard measure within the meaning of the Safeguards Agreement against the goods of the other Party from the date of entry into force of this Agreement.

*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 4(Scope and Coverage)
*** SAFTA: most similar Title = 15(Safeguard Measures)
*** SAFTA: most similar Body = 15(Safeguard Measures)

** 2.19 Publication and Administration of Trade Regulations
:length: 108
*** body

Article X of the GATT 1994 is incorporated into and shall form part of this Agreement, *mutatis mutandis*.
*** CSFTA: most similar Title = 5(National Treatment on Internal Taxation and Regulation)
*** CSFTA: most similar Body = 4(Scope and Coverage)
*** SAFTA: most similar Title = 7(Temporary Admission of Goods)
*** SAFTA: most similar Body = 16(Transparency)


* FTA/1. Goods/CSFTA/Chapter 3 - Trade in Goods.md
**  __PREAMBLE
:length: 30
*** body
**CHAPTER 3 TRADE IN GOODS**

*** ANZSCEP: most similar Title = ?(__PREAMBLE)
*** ANZSCEP: most similar Body = ?(__PREAMBLE)
*** SAFTA: most similar Title = ?(__PREAMBLE)
*** SAFTA: most similar Body = ?(__PREAMBLE)

** 4 Scope and Coverage
:length: 88
*** body
This Chapter applies to trade in goods between the Parties, unless otherwise provided.

*** ANZSCEP: most similar Title = 2.2(Scope)
*** ANZSCEP: most similar Body = ?(__PREAMBLE)
*** SAFTA: most similar Title = 15(Safeguard Measures)
*** SAFTA: most similar Body = 16(Transparency)

** 5 National Treatment on Internal Taxation and Regulation
:length: 278
*** body
Each Party shall accord national treatment to the goods of the other Party in accordance with Article III of the GATT 1994. To this end, the provisions of Article III of the GATT 1994 shall, *mutatis mutandis*, be incorporated into and form an integral part of this Agreement.

*** ANZSCEP: most similar Title = 2.3(National Treatment on Internal Taxation and Regulation)
*** ANZSCEP: most similar Body = 2.3(National Treatment on Internal Taxation and Regulation)
*** SAFTA: most similar Title = 2(National Treatment on Internal Taxation and Regulation)
*** SAFTA: most similar Body = 2(National Treatment on Internal Taxation and Regulation)

** 6 Customs Duties
:length: 1453
*** body
1.  The tariff lines that are subject to the tariff reduction or elimination programme under this Agreement are all the tariff lines covered under the Normal Track, as specified in Article 3(2)(a) of the *Agreement on Trade in Goods of the Framework Agreement on Comprehensive Economic Co-operation between the Association of Southeast Asian Nations and the People's Republic of China* done on 29 November 2004 (the "ASEAN-China Trade in Goods Agreement"), read with Annex 1 thereof. In the case of Singapore, this Agreement shall also include all tariff lines covered under the Sensitive Track, as specified in Article 3(2)(b) of the ASEAN-China Trade in Good Agreement, read with Annex 2 thereof^1^.

2.  Except as otherwise provided in this Agreement, and subject to paragraph 1 as well as a Party's Tariff Elimination Schedule as set out in Annex 1 (Tariff Elimination Schedules), on the date of entry into force of this Agreement, each Party shall eliminate its customs duties on originating goods of the other Party.

3.  Except as otherwise provided in this Agreement, either Party shall not increase any existing duty or introduce a new customs duty on an originating good of the other Party.

^1^ For greater certainty, in the case of China, tariff lines covered under the Sensitive Track, as specified in Article 3(2)(b) of the ASEAN-China Trade in Goods Agreement, read with Annex 2 thereof, shall continue to be governed by that Agreement.

*** ANZSCEP: most similar Title = 2.4(Customs Duties)
*** ANZSCEP: most similar Body = 2.7(Goods Re-entered after Repair and Alteration)
*** SAFTA: most similar Title = 3(Customs Duties)
*** SAFTA: most similar Body = 5(Goods Re-entered after Repair and Alteration)

** 7 Accelerated Tariff Elimination
:length: 839
*** body
1.  At the request of either Party, the Parties shall consult to consider accelerating the elimination of customs duties on originating goods as set out in their Tariff Elimination Schedules in Annex 1 (Tariff Elimination Schedules).

2.  An agreement by the Parties to accelerate the elimination of customs duties on originating goods shall supersede any duty rate determined pursuant to their Schedules for such goods, and shall enter into force following approval by each Party in accordance with their applicable legal procedures.

3.  A Party may at any time accelerate unilaterally the elimination of customs duties on originating goods of the other Party set out in its Tariff Elimination Schedule. A Party considering doing so shall inform the other Party as early as practicable before the new rate of customs duty takes effect.

*** ANZSCEP: most similar Title = 2.10(Import and Export Restrictions)
*** ANZSCEP: most similar Body = 2.15(Non-tariff Measures)
*** SAFTA: most similar Title = 18(General Exceptions)
*** SAFTA: most similar Body = 3(Customs Duties)

** 8 Quantitative Restrictions and Non-Tariff Measures
:length: 708
*** body
1.  Each Party undertakes not to maintain any quantitative restrictions at any time unless otherwise permitted under the WTO disciplines.

2.  Neither Party shall adopt or maintain any non-tariff measure on the importation of any good of the other Party or on the exportation of any good destined for the territory of the other Party, except in accordance with its WTO rights and obligations, or in accordance with other provisions of this Agreement.

3.  Each Party shall ensure the transparency of its non-tariff measures permitted under paragraph 1 above and that they are not prepared, adopted or applied with a view to or with the effect of creating unnecessary obstacles to trade between the Parties.

*** ANZSCEP: most similar Title = 2.15(Non-tariff Measures)
*** ANZSCEP: most similar Body = 2.15(Non-tariff Measures)
*** SAFTA: most similar Title = 12(Non-tariff Measures)
*** SAFTA: most similar Body = 12(Non-tariff Measures)

** 9 State Trading Enterprises
:length: 174
*** body
Nothing in this Agreement shall be construed to prevent a Party from maintaining or establishing a state trading enterprise in accordance with Article XVII of the GATT 1994.
*** ANZSCEP: most similar Title = 2.17(Antidumping Measures)
*** ANZSCEP: most similar Body = 2.2(Scope)
*** SAFTA: most similar Title = 18(General Exceptions)
*** SAFTA: most similar Body = 4(Customs Value)


* FTA/1. Goods/SAFTA/Chapter 2 -Trade in Goods.md
**  __PREAMBLE
:length: 0
*** body
*** ANZSCEP: most similar Title = ?(__PREAMBLE)
*** ANZSCEP: most similar Body = ?(__PREAMBLE)
*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = ?(__PREAMBLE)

** 1 Definitions
:length: 5457
*** body
For the purposes of this Chapter:

(a) "AD Agreement" means the *Agreement on Implementation of Article VI of the General Agreement on Tariffs and Trade 1994*, set out in Annex 1A to the WTO Agreement;

(b) "advertising films and recordings" means recorded visual media or audio materials, consisting essentially of images or sound, showing the nature or operation of goods or services offered for sale or lease by a person of a Party, that are of a kind suitable for exhibition to prospective customers but not for broadcast to the general public;

(c) "Agreement on Agriculture" means the *Agreement on Agriculture*, set out in Annex 1A to the WTO Agreement;

(d) "commercial samples of negligible value" means commercial or trade samples: having a value, individually or in the aggregate as shipped, of not more than one U.S. dollar or the equivalent amount in the currency of either Party; or so marked, torn, perforated or otherwise treated that they are unsuitable for sale or for use except as commercial samples;

(e) "consumed" means, with respect to a good:

    i.  actually consumed; or

    ii. further processed or manufactured:

        A.  so as to result in a substantial change in the value, form or use of the good; or

        B.  in the production of another good;

(f) "distributor" means a person of a Party who is responsible for the commercial distribution, agency, concession or representation in the territory of that Party of goods of another Party;

(g) "duty-free" means free of customs duty;

(h) "enterprise" means any entity constituted or organised under applicable law, whether or not for profit, and whether privately or governmentally owned or controlled, including any corporation, trust, partnership, sole proprietorship, joint venture, association or similar organisation;

(i) "export subsidy" means a subsidy as defined by Article 3 of the SCM Agreement and includes export subsidies listed in Article 9 of the Agreement on Agriculture;

(j) "goods" means any merchandise, product, article or material;

(k) "goods admitted for sports purposes" means sports requisites admitted into the territory of the importing Party for use in sports contests, demonstrations or training in the territory of that Party;

(l) "goods intended for display or demonstration" includes their component parts, ancillary apparatuses and accessories;

(m) "import licensing" means an administrative procedure requiring the submission of an application or other documentation, other than that generally required for customs clearance purposes, to the relevant administrative body of the importing Party as a prior condition for importation into the territory of that Party;

(n) "Import Licensing Agreement" means the *Agreement on Import Licensing Procedures*, set out in Annex 1A to the WTO Agreement;

(o) "measure" includes any law, regulation, procedure, requirement or practice;

(p) "national" means:

    i.  for Australia, a natural person who is an Australian citizen as defined in the *Australian Citizenship Act 2007*, as amended from time to time, or any successor legislation;

    ii. for Singapore, a person who is a citizen of Singapore within the meaning of its Constitution and its domestic laws; or

    iii. a permanent resident of either Party;

(q) "performance requirement" means a requirement that:

    i.  a given level or percentage of goods or services be exported;

    ii. domestic goods or services of the Party granting a waiver of customs duties or an import licence be substituted for imported goods;

    iii. a person benefiting from a waiver of customs duties or a requirement for an import licence purchase other goods or services in the territory of the Party that grants the waiver of customs duties or the import licence or accord a preference to domestically produced goods;

    iv. a person benefiting from a waiver of customs duties or a requirement for an import licence produce goods or supply services in the territory of the Party that grants the waiver of customs duties or the import licence, with a given level or percentage of domestic content; or

    v.  relates in any way the volume or value of imports to the volume or value of exports or to the amount of foreign exchange inflows;

but does not include a requirement that an imported good be:

vi. subsequently exported;

vii. used as a material in the production of another good that is subsequently exported;

viii. substituted by an identical or similar good used as a material in the production of another good that is subsequently exported; or

ix. substituted by an identical or similar good that is subsequently exported;

```{=html}
<!-- -->
```
(r) "person" means a natural person or an enterprise;

(s) "person of a Party" means a national or an enterprise of a Party;

(t) "printed advertising materials" means those goods classified in Chapter 49 of the Harmonized System, including brochures, pamphlets, leaflets, trade catalogues, yearbooks published by trade associations, tourist promotional materials and posters, that are used to promote, publicise or advertise a good or service, are essentially intended to advertise a good or service, and are supplied free of charge;

(u) "Safeguards Agreement" means the *Agreement on Safeguards*, set out in Annex 1A to the WTO Agreement; and

(v) "SCM Agreement" means the *Agreement on Subsidies and Countervailing Measures*, set out in Annex 1A to the WTO Agreement.

*** ANZSCEP: most similar Title = 2.1(Definitions)
*** ANZSCEP: most similar Body = 2.1(Definitions)
*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 6(Customs Duties)

** 2 National Treatment on Internal Taxation and Regulation
:length: 313
*** body
Each Party shall accord national treatment to the goods of the other Party in accordance with Article III of the GATT 1994, including its interpretative notes. To this end, Article III of the GATT 1994 and its interpretative notes are incorporated into and shall form part of this Agreement, *mutatis mutandis*.

*** ANZSCEP: most similar Title = 2.3(National Treatment on Internal Taxation and Regulation)
*** ANZSCEP: most similar Body = 2.3(National Treatment on Internal Taxation and Regulation)
*** CSFTA: most similar Title = 5(National Treatment on Internal Taxation and Regulation)
*** CSFTA: most similar Body = 5(National Treatment on Internal Taxation and Regulation)

** 3 Customs Duties
:length: 424
*** body
1.  Each Party shall eliminate all customs duties on goods originating in the territory of the other Party that meet the requirements for originating goods as set out in Chapter 3 (Rules of Origin). All customs duties on such goods shall thereby be free from the date of entry into force of this Agreement.

2.  The classification of goods traded between the Parties shall be in conformity with the Harmonized System (HS).

*** ANZSCEP: most similar Title = 2.4(Customs Duties)
*** ANZSCEP: most similar Body = 2.4(Customs Duties)
*** CSFTA: most similar Title = 6(Customs Duties)
*** CSFTA: most similar Body = 5(National Treatment on Internal Taxation and Regulation)

** 4 Customs Value
:length: 197
*** body
The Parties shall determine the customs value of goods traded between them in accordance with Article VII of the GATT 1994 and the WTO Agreement on Implementation of Article VII of the GATT 1994.

*** ANZSCEP: most similar Title = 2.6(Customs Value)
*** ANZSCEP: most similar Body = 2.6(Customs Value)
*** CSFTA: most similar Title = 6(Customs Duties)
*** CSFTA: most similar Body = 9(State Trading Enterprises)

** 5 Goods Re-entered after Repair and Alteration
:length: 896
*** body
1.  Neither Party shall apply a customs duty to a good, regardless of its origin, that re-enters the Party's territory after that good has been temporarily exported from the Party's territory to the territory of the other Party for repair or alteration, regardless of whether that repair or alteration could have been performed in the territory of the Party from which the good was exported for repair or alteration or increased the value of the good.

2.  Neither Party shall apply a customs duty to a good, regardless of its origin, admitted temporarily from the territory of the other Party for repair or alteration.

3.  For the purposes of this Article, "repair or alteration" does not include an operation or process that:

    a.  destroys a good's essential characteristics or creates a new or commercially different good; or

    b.  transforms an unfinished good into a finished good.

*** ANZSCEP: most similar Title = 2.7(Goods Re-entered after Repair and Alteration)
*** ANZSCEP: most similar Body = 2.7(Goods Re-entered after Repair and Alteration)
*** CSFTA: most similar Title = 7(Accelerated Tariff Elimination)
*** CSFTA: most similar Body = 8(Quantitative Restrictions and Non-Tariff Measures)

** 6 Duty-Free Entry of Commercial Samples of Negligible Value and Printed Advertising Material
:length: 592
*** body
Each Party shall grant duty-free entry to commercial samples of negligible value and printed advertising material imported from the territory of the other Party, regardless of their origin, but may require that:

(a) commercial samples of negligible value be imported solely for the solicitation of orders for goods, or services provided from the territory, of another Party or a non-Party; or

(b) printed advertising material be imported in packets that each contain no more than one copy of the material and that neither that material nor those packets form part of a larger consignment.

*** ANZSCEP: most similar Title = 2.8(Duty-Free Entry of Commercial Samples of Negligible Value and Printed Advertising Material)
*** ANZSCEP: most similar Body = 2.8(Duty-Free Entry of Commercial Samples of Negligible Value and Printed Advertising Material)
*** CSFTA: most similar Title = 5(National Treatment on Internal Taxation and Regulation)
*** CSFTA: most similar Body = 5(National Treatment on Internal Taxation and Regulation)

** 7 Temporary Admission of Goods
:length: 5318
*** body
1.  Each Party shall grant duty-free temporary admission for the following goods, regardless of their origin:

    a.  professional equipment, including equipment for the press or television, software, and broadcasting and cinematographic equipment, that is necessary for carrying out the business activity, trade or profession of a person who qualifies for temporary entry pursuant to the laws of the importing Party;

    b.  goods intended for display or demonstration;

    c.  commercial samples and advertising films and recordings; and

    d.  goods admitted for sports purposes.

2.  Each Party shall, at the request of the person concerned and for reasons its customs authority considers valid, extend the time limit for duty-free temporary admission beyond the period initially fixed.

3.  Neither Party shall condition the duty-free temporary admission of the goods referred to in paragraph 1, other than to require that those goods:

    a.  be used solely by or under the personal supervision of a national of the other Party in the exercise of the business activity, trade, profession or sport of that national of the other Party;

    b.  not be sold or leased while in its territory;

    c.  be accompanied by a security in an amount no greater than the charges that would otherwise be owed on entry or final importation, releasable on exportation of the goods;

    d.  be capable of identification when imported and exported;

    e.  be exported on the departure of the national referred to in subparagraph (a), or within any other period reasonably related to the purpose of the temporary admission that the Party may establish, or within one year, unless extended;

    f.  be admitted in no greater quantity than is reasonable for their intended use; and

    g.  be otherwise admissible into the Party's territory under its laws.

4.  Each Party shall grant duty-free temporary admission for containers and pallets regardless of their origin, that are in use or to be used in the shipment of goods in international traffic.

    a.  For the purposes of this paragraph, "container" means an article of transport equipment that is: fully or partially enclosed to constitute a compartment intended for containing goods; substantial and has an internal volume of one cubic metre or more; of a permanent character and accordingly strong enough to be suitable for repeated use; used in significant numbers in international traffic; specially designed to facilitate the carriage of goods by more than one mode of transport without intermediate reloading; and designed both for ready handling, particularly when being transferred from one mode of transport to another, and to be easy to fill and to empty, but does not include vehicles, accessories or spare parts of vehicles or packaging.

    b.  For the purposes of this paragraph, "pallet" means a small, portable platform, which consists of two decks separated by bearers or a single deck supported by feet, on which goods can be moved, stacked, and stored, and which is designed essentially for handling by means of fork lift trucks, pallet trucks, or other jacking devices.

5.  If any condition that a Party imposes under paragraph 3 has not been fulfilled, the Party may apply the customs duty and any other charge that would normally be owed on the good in addition to any other charges or penalties provided for under its law.

6.  Each Party shall adopt and maintain procedures providing for the expeditious release of goods admitted under this Article. To the extent possible, those procedures shall provide that when a good admitted under this Article accompanies a national of the other Party who is seeking temporary entry, the good shall be released simultaneously with the entry of that national.

7.  Each Party shall permit a good temporarily admitted under this Article to be exported through a customs port other than the port through which it was admitted.

8.  Each Party shall, in accordance with its laws, provide that the importer or other person responsible for a good admitted under this Article shall not be liable for failure to export the good on presentation of satisfactory proof to the importing Party that the good was destroyed within the period fixed for temporary admission, including any lawful extension.

9.  Subject to Chapters 7 (Cross-Border Trade in Services) and 8 (Investment):

    a.  each Party shall allow a container used in international traffic that enters its territory from the territory of the other Party to exit its territory on any route that is reasonably related to the economic and prompt departure of that container;

    b.  neither Party shall require any security or impose any penalty or charge solely by reason of any difference between the customs port of entry and the customs port of departure of a container;

    c.  neither Party shall condition the release of any obligation, including any security, that it imposes in respect of the entry of a container into its territory on the exit of that container through any particular customs port of departure; and

    d.  neither Party shall require that the carrier bringing a container from the territory of the other Party into its territory be the same carrier that takes such container to the territory of the other Party.

*** ANZSCEP: most similar Title = 2.9(Temporary Admission of Goods)
*** ANZSCEP: most similar Body = 2.9(Temporary Admission of Goods)
*** CSFTA: most similar Title = 9(State Trading Enterprises)
*** CSFTA: most similar Body = 6(Customs Duties)

** 8 Import and Export Restrictions
:length: 2904
*** body
1.  Except as otherwise provided in this Agreement, neither Party shall adopt or maintain any prohibition or restriction on the importation of any good of the other Party or on the exportation or sale for export of any good destined for the territory of the other Party, except in accordance with Article XI of the GATT 1994 and its interpretative notes, and to this end Article XI of the GATT 1994 and its interpretative notes are incorporated into and made part of this Agreement, *mutatis mutandis*.

2.  The Parties understand that the GATT 1994 rights and obligations incorporated by paragraph 1 prohibit, in any circumstances in which any other form of restriction is prohibited, a Party from adopting or maintaining:

    a.  export and import price requirements, except as permitted in enforcement of countervailing and anti-dumping duty orders and undertakings;

    b.  import licensing conditioned on the fulfilment of a performance requirement; or

    c.  voluntary export restraints inconsistent with Article VI of the GATT 1994, as implemented under Article 18 of the SCM Agreement and Article 8.1 of the AD Agreement.

3.  For greater certainty, paragraph 1 shall apply to the importation of commercial cryptographic goods.

4.  For the purposes of paragraph 3, "commercial cryptographic goods" means any good implementing or incorporating cryptography, if the good is not designed or modified specifically for government use and is sold or otherwise made available to the public.

5.  In the event that a Party adopts or maintains a prohibition or restriction on the importation from or exportation to a non-Party of a good, no provision of this Agreement shall be construed to prevent that Party from:

    a.  limiting or prohibiting the importation of the good of the non-Party from the territory of the other Party; or

    b.  requiring, as a condition for exporting the good of that Party to the territory of the other Party, that the good not be re-exported to the non- Party, directly or indirectly, without being consumed in the territory of the other Party.

6.  In the event that a Party adopts or maintains a prohibition or restriction on the importation of a good from a non-Party, it shall, on the request of the other Party, consult with the other Party a view to avoiding undue interference with or distortion of pricing, marketing, or distribution arrangements in that other Party.

7.  Neither Party shall, as a condition for engaging in importation or for the importation of a good, require a person of the other Party to establish or maintain a contractual or other relationship with a distributor in its territory.

8.  For greater certainty, paragraph 7 does not prevent a Party from requiring a person referred to in that paragraph to designate a point of contact for the purpose of facilitating communications between its regulatory authorities and that person.

*** ANZSCEP: most similar Title = 2.10(Import and Export Restrictions)
*** ANZSCEP: most similar Body = 2.10(Import and Export Restrictions)
*** CSFTA: most similar Title = 4(Scope and Coverage)
*** CSFTA: most similar Body = 6(Customs Duties)

** 9 Remanufactured Goods
:length: 327
*** body
1.  For greater certainty, Article 8.1 (Import and Export Restrictions) shall apply to prohibitions and restrictions on the importation of remanufactured goods.

2.  If a Party adopts or maintains measures prohibiting or restricting the importation of used goods, it shall not apply those measures to remanufactured goods.^1^

*** ANZSCEP: most similar Title = 2.11(Remanufactured Goods)
*** ANZSCEP: most similar Body = 2.11(Remanufactured Goods)
*** CSFTA: most similar Title = 4(Scope and Coverage)
*** CSFTA: most similar Body = 9(State Trading Enterprises)

** 10 Import Licensing
:length: 4971
*** body
1.  Neither Party shall adopt or maintain a measure that is inconsistent with the Import Licensing Agreement.

2.  Promptly after this Agreement enters into force for a Party, that Party shall notify the other Parties of its existing import licensing procedures, if any. The notice shall include the information specified in Article 5.2 of the Import Licensing Agreement and any information required under paragraph 6.

3.  A Party shall be deemed to be in compliance with paragraph 2 with respect to an existing import licensing procedure if:

    a.  it has notified that procedure to the WTO Committee on Import Licensing provided for in Article 4 of the Import Licensing Agreement together with the information specified in Article 5.2 of that agreement;

    b.  in the most recent annual submission due before the date of entry into force of the Agreement to Amend the Singapore-Australia Free Trade Agreement for that Party to the WTO Committee on Import Licensing in response to the annual questionnaire on import licensing procedures described in Article 7.3 of the Import Licensing Agreement, it has provided, with respect to that procedure, the information requested in that questionnaire; and

    c.  it has included in either the notice described in subparagraph (a) or the annual submission described in subparagraph (b) any information required to be notified to the other Party under paragraph 6.

4.  Each Party shall comply with Article 1.4(a) of the Import Licensing Agreement with respect to any new or modified import licensing procedure. Each Party shall also publish on an official government website any information that it is required to publish under Article 1.4(a) of the Import Licensing Agreement.

5.  Each Party shall notify the other Party of any new import licensing procedures it adopts and any modifications it makes to its existing import licensing procedures, if possible, no later than 60 days before the new procedure or modification takes effect.

^1^ For greater certainty, subject to its obligations under this Agreement and the WTO Agreement, a Party may require that remanufactured goods:

a.  be identified as such for distribution or sale in its territory; and

b.  meet all applicable technical requirements that apply to equivalent goods in new condition.

In no case shall a Party provide the notification later than 60 days after the date of its publication. The notification shall include any information required under paragraph 6. A Party shall be deemed to be in compliance with this obligation if it notifies a new import licensing procedure or a modification to an existing import licensing procedure to the WTO Committee on Import Licensing in accordance with Articles 5.1, 5.2 or 5.3 of the Import Licensing Agreement, and includes in its notification any information required to be notified to the other Party under paragraph 6.

6.  \(a\) A notice under paragraph 2, paragraph 3 or paragraph 5 shall state if, under any import licensing procedure that is a subject of the notice:

```{=html}
<!-- -->
```
(i) the terms of an import licence for any product limit the permissible end users of the product; or

(ii) the Party imposes any of the following conditions on eligibility for obtaining a licence to import any product:

     A.  membership in an industry association;

     B.  approval by an industry association of the request for an import licence;

     C.  a history of importing the product or similar products;

     D.  minimum importer or end user production capacity;

     E.  minimum importer or end user registered capital; or

     F.  a contractual or other relationship between the importer and a distributor in the Party's territory.

```{=html}
<!-- -->
```
(b) A notice that states, under subparagraph (a), that there is a limitation on permissible end users or a licence-eligibility condition shall:

    i.  list all products for which the end-user limitation or licence eligibility condition applies; and

    ii. describe the end-user limitation or licence-eligibility condition.

```{=html}
<!-- -->
```
7.  Each Party shall respond within 60 days to a reasonable enquiry from the other Party concerning its licensing rules and its procedures for the submission of an application for an import licence, including the eligibility of persons, firms and institutions to make an application, the administrative body or bodies to be approached and the list of products subject to the licensing requirement.

8.  If a Party denies an import licence application with respect to a good of the other Party, it shall, on request of the applicant and within a reasonable period after receiving the request, provide the applicant with a written explanation of the reason for the denial.

9.  Neither Party shall apply an import licensing procedure to a good of the other Party unless it has, with respect to that procedure, met the requirements of paragraph 2 or paragraph 4, as applicable.

*** ANZSCEP: most similar Title = 2.12(Import Licensing)
*** ANZSCEP: most similar Body = 2.12(Import Licensing)
*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 6(Customs Duties)

** 11 Export Duties
:length: 161
*** body
A Party shall not impose any export duty on the goods set out in Annex 1 (Export Duties), when exported from its territory to the territory of the other Party.

*** ANZSCEP: most similar Title = 2.14(Export Duties)
*** ANZSCEP: most similar Body = 2.6(Customs Value)
*** CSFTA: most similar Title = 6(Customs Duties)
*** CSFTA: most similar Body = 4(Scope and Coverage)

** 12 Non-tariff Measures
:length: 544
*** body
1.  Neither Party shall adopt or maintain any non-tariff measures on the importation of any good of the other Party or on the exportation of any good destined for the territory of the other Party except in accordance with its WTO rights and obligations or in accordance with this Agreement*.*

2.  Each Party shall ensure the transparency of its non-tariff measures permitted under paragraph 1 and that they are not prepared, adopted or applied with a view to or with the effect of creating unnecessary obstacles to trade between the Parties.

*** ANZSCEP: most similar Title = 2.15(Non-tariff Measures)
*** ANZSCEP: most similar Body = 2.15(Non-tariff Measures)
*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 8(Quantitative Restrictions and Non-Tariff Measures)

** 13 Subsidies and Countervailing Measures
:length: 170
*** body
1.  The Parties agree to prohibit export subsidies on all goods, including agricultural goods.

2.  The Parties reaffirm their commitment to abide by the SCM Agreement.

*** ANZSCEP: most similar Title = 2.16(Subsidies and Countervailing Measures)
*** ANZSCEP: most similar Body = 2.19(Publication and Administration of Trade Regulations)
*** CSFTA: most similar Title = 4(Scope and Coverage)
*** CSFTA: most similar Body = 4(Scope and Coverage)

** 14 Anti-Dumping Measures
:length: 1697
*** body
1.  With respect to the application of anti-dumping measures, the Parties reaffirm their commitment to the AD Agreement.

2.  The Parties agree to observe the following practices in anti-dumping cases between them:

    a.  the time frame to be used for determining the volume of dumped imports in an investigation or review shall be representative of the imports of

both dumped and non-dumped goods, for a reasonable period, and such reasonable period shall normally be at least 12 months;

b.  if a decision is taken to impose an anti-dumping duty pursuant to Article

9.1 of the AD Agreement, the Party taking such a decision shall normally apply the "lesser duty rule" by imposing a duty which is less than the dumping margin where such lesser duty would be adequate to remove the injury to the domestic industry; and

c.  notification procedures shall be as follows:

    i.  immediately following the acceptance by a Party of a properly documented application from an industry in that Party for the initiation of an anti-dumping investigation in respect of goods from the other Party, the first Party shall immediately inform the other Party;

    ii. where a Party considers that, in accordance with Article 5 of the AD Agreement, there is sufficient evidence to justify the initiation of an anti-dumping investigation, it shall give written notice to the other Party and shall act in accordance with Article

17.2 of that Agreement concerning consultations.

3.  At reviews of this Agreement under Article 7 (Review) of Chapter 17 (Final Provisions), the Parties shall review this Article, including a consideration of any recommendations by the WTO Committee on Anti-Dumping Practices.

*** ANZSCEP: most similar Title = 2.17(Antidumping Measures)
*** ANZSCEP: most similar Body = 2.13(Administrative Fees and Formalities)
*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 6(Customs Duties)

** 15 Safeguard Measures
:length: 195
*** body
A Party shall not initiate or take any safeguard measure within the meaning of the Safeguards Agreement against the goods of the other Party from the date of entry into force of this Agreement.

*** ANZSCEP: most similar Title = 2.18(Safeguard Measures)
*** ANZSCEP: most similar Body = 2.18(Safeguard Measures)
*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 4(Scope and Coverage)

** 16 Transparency
:length: 108
*** body
Article X of the GATT 1994 is incorporated into and shall form part of this Agreement, *mutatis mutandis*.

*** ANZSCEP: most similar Title = 2.2(Scope)
*** ANZSCEP: most similar Body = 2.19(Publication and Administration of Trade Regulations)
*** CSFTA: most similar Title = ?(__PREAMBLE)
*** CSFTA: most similar Body = 4(Scope and Coverage)

** 17 Measures to Safeguard the Balance of Payments
:length: 258
*** body
Where a Party is in serious balance of payments and external financial difficulties or threat thereof, it may, in accordance with the GATT 1994 and the Understanding on the Balance-of-Payments Provisions of the GATT 1994, adopt restrictive import measures.

*** ANZSCEP: most similar Title = 2.18(Safeguard Measures)
*** ANZSCEP: most similar Body = 2.6(Customs Value)
*** CSFTA: most similar Title = 9(State Trading Enterprises)
*** CSFTA: most similar Body = 9(State Trading Enterprises)

** 18 General Exceptions
:length: 2379
*** body
Subject to the requirement that such measures are not applied in a manner which would constitute a means of arbitrary or unjustifiable discrimination between the Parties where the same conditions prevail, or a disguised restriction on international trade, nothing in this Chapter shall be construed to prevent the adoption or enforcement by a Party of measures:

a.  necessary to protect public morals;

b.  necessary to protect human, animal or plant life or health;

c.  relating to the importations or exportations of gold or silver;

d.  necessary to secure compliance with laws or regulations which are not inconsistent with this Chapter, including those relating to customs enforcement, the enforcement of monopolies operated under paragraph 4 of Article II and Article XVII of the GATT 1994, the protection of patents, trademarks and copyrights, and the prevention of deceptive practices;

e.  relating to the products of prison labour;

f.  imposed for the protection of national treasures of artistic, historic or archaeological value;

g.  relating to the conservation of exhaustible natural resources if such measures are made effective in conjunction with restrictions on domestic production or consumption;

h.  undertaken in pursuance of obligations under any intergovernmental commodity agreement which conforms to criteria submitted to the WTO and not disapproved by it or which is itself so submitted and not so disapproved;

i.  involving restrictions on exports of domestic materials necessary to ensure essential quantities of such materials to a domestic processing industry during periods when the domestic price of such materials is held below the world price as part of a governmental stabilization plan; Provided that such restrictions shall not operate to increase the exports of or the protection afforded to such domestic industry, and shall not

depart from the provisions of this Chapter relating to non- discrimination;

j.  essential to the acquisition or distribution of products in general or local short supply; Provided that any such measures shall be consistent with the principle that all WTO members are entitled to an equitable share of the international supply of such products, and that any such measures, which are inconsistent with this Chapter shall be discontinued as soon as the conditions giving rise to them have ceased to exist.
*** ANZSCEP: most similar Title = 2.1(Definitions)
*** ANZSCEP: most similar Body = 2.16(Subsidies and Countervailing Measures)
*** CSFTA: most similar Title = 6(Customs Duties)
*** CSFTA: most similar Body = 6(Customs Duties)



